### ISSUE TITLE
Pack with UnrealPak.exe

### ISSUE THREAD

**Issue by arashberlin** [masterj1337/IcarusMods#1]
Nice work. 

Sorry for the newbie questions.  I like the game and like to tweak it to have more fun.

Do I need to pack the json file with the right UE Engine(4.26.2)?

I tried some other Weight and MaxStack parameters. Packet the file with the UE 4.27.2 as follows:

Unpack:
"c:\Program Files\Epic Games\UE_4.27\Engine\Binaries\Win64\UnrealPak.exe" -Extract D:\icarus\t\j2g_stackSizeIncrease_P.pak D:\icarus\t\j2g_stackSizeIncrease_P 

Pack:
"c:\Program Files\Epic Games\UE_4.27\Engine\Binaries\Win64\UnrealPak.exe" D:\icarus\t\j2g_stackSizeIncrease_P.pak -Create D:\icarus\t\j2g_stackSizeIncrease_P\D_Itemable.json -Compress

Do I need to use the -Compress param?

With the changed variant nothing happens in game. Standard Weight/MaxStack are used.

Without change, no issue :)

Best Regards.

**Comment by masterj1337** [comment]
I want to start by recommending you join the modding discord, a bunch of helpful people (including myself) and Tools/Guides posted by the LNKR who created it. https://discord.gg/GC8smJwhQt

Use this version of DRG Packer, simply drag on unpack.bat to unpack it and then onto re-pack.bat to re-pack it. Word of caution, it wont always pick up the file structure. My mod for instance has a JSON file which lives in <ModFolder>/Data/Traits/file.json. When unpacked you may get <ModFolder>/file.json, so make sure you rebuild the folder structure. you can get this info by dropping the pak onto the about.bat and checking the mountpoint. Rebuild everything after Content/.

DRGPacker:
https://drive.google.com/file/d/1Jf8YNuBSKgXsTjZpyAzjnWkeYzDQ_Zzq/view

I haven't had to deal with UAsset files so I just use Notepad++ and this packing tool to do everything.

**Comment by arashberlin** [comment]
many thanks.
